# Generated by Django 4.2 on 2024-03-22 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='end_lat',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='end_long',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='start_lat',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='start_long',
        ),
        migrations.CreateModel(
            name='BikeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=59.90756, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(default=10.7599, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bike')),
            ],
        ),
    ]
