# Generated by Django 4.2 on 2024-05-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_bike_latitude_remove_bike_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikelocation',
            options={'ordering': ['-time']},
        ),
    ]
