# Generated by Django 4.2 on 2024-03-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerental',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='end_station',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='start_station',
        ),
        migrations.RemoveField(
            model_name='bikerental',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriptiontype',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.DeleteModel(
            name='BikeRental',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
    ]
